### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by ModMaker101** [Bedrock-OSS/bedrock-wiki#627] opened 2023-04-13 13:10 UTC
Issue: When I refreshed the page on custom tree the syntax highlighting disappeared 

Affected pages: It's harder to read without syntax highlighting.

Suggestions: I don't know.
![Uploading Screenshot 2023-04-13 090635.png…]()

**Comment by SmokeyStack** [comment] 2023-04-13 13:35
Duplicate of #383

**Closed by SmokeyStack** 2023-04-13 13:35 UTC
Labels: BUG
